// src/app/T&C/page.tsx

import Footer from "@/components/footer";
import Header from "@/components/header";

export default function TermsAndConditionsPage() {
  return (
    <>
      <Header />
      <main className="container mx-auto max-w-4xl px-4 py-12">
        <div className="space-y-8">
          <h1 className="text-3xl font-bold tracking-tight">Terms & Conditions</h1>
          <p className="text-sm text-muted-foreground">Last updated: June 18, 2024</p>

          <div className="prose prose-lg max-w-none">
            <p>1. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
            <p>2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <strong>https://wall-street-ind.vercel.app</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
            <p>3. The Platform is owned by <strong>WallStreet</strong>, <strong>a sole proprietorship</strong> with its registered office at <strong> Ramprastha Colony, Ghaziabad, India</strong> (hereinafter referred to as ‘Platform Owner', 'we', 'us', 'our').</p>
            <p>4. Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform... By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.</p>
            <p>5. For the purpose of these Terms of Use, wherever the context so requires ‘you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
            <p>6. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</p>
            <p>7. The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
            <ol className="list-decimal pl-6">
              <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
              <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose...</li>
              <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner...</li>
              <li>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents...</li>
              <li>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
              <li>You agree to pay us the charges associated with availing the Services.</li>
              <li>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
              <li>You agree and acknowledge that website and the Services may contain links to other third party websites...</li>
              <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
            </ol>
            <p>10. You shall indemnify and hold harmless Platform Owner, its affiliates... from any claim or demand... arising out of Your breach of this Terms of Use, privacy Policy and other Policies...</p>
            <p>11. Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
            <p>12. These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</p>
            <p>13. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong>Ghaziabad and Uttar Pradesh</strong>.</p>
            <p>14. All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}